os: linux
dist: bionic
language: cxx
jobs:
    include:
        - env: UCX_VERSION=master
          compiler: clang
        - env: UCX_VERSION=v1.9.x
          compiler: clang
        - env: UCX_VERSION=v1.8.x
          compiler: clang

before_install:
    - sudo apt-get update
    - sudo apt-get install -y clang-format-8 autotools-dev libtool libnuma-dev
    - git clone https://github.com/openucx/ucx.git && cd ucx && git checkout $UCX_VERSION && ./autogen.sh && ./configure --prefix=/usr --disable-gtest --disable-examples && make -j4 && sudo make install

script:
    - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
    - ./autogen.sh
    - ./configure
    - make
