os: linux
dist: bionic
language: c
compiler: clang
# jobs:
#     include:
#         - env: UCX_VERSION=master
#         - env: UCX_VERSION=v1.9.x
#         - env: UCX_VERSION=v1.8.x

before_install:
    - sudo apt-get update
    - sudo apt-get install -y clang-format-8 autotools-dev libtool libnuma-devel
    - git clone https://github.com/openucx/ucx.git && cd ucx && ./autogen.sh && ./configure --prefix=/usr && make -j4 install

script:
    - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
    - ./autogen.sh
    - ./configure
    - make
